language: csharp
dist: xenial
dotnet: 6.0.100
mono: none
env: CONFIGURATION=Release FRAMEWORK=net6.0

before_script:
  - dotnet --info
  - dotnet restore

script:
  - dotnet test -c $CONFIGURATION -f $FRAMEWORK tests/NSubstitute.Acceptance.Specs/NSubstitute.Acceptance.Specs.csproj
