export const Assets = [
  {
    name: "bathroom",
    key: "bathroom",
    folder: "/mesh/bathroom/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "bathroom_shower_glass",
    key: "bathroom_shower_glass",
    folder: "/mesh/bathroom_shower_glass/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "bathroom_walls",
    key: "bathroom_walls",
    folder: "/mesh/bathroom_walls/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [
      // {
      //   selected: "selected",
      //   value: "furMat",
      //   name: "furMat",
      //   key: "WelcomeWallMat",
      //   url: "https://www.babylonjs-playground.com/textures/fur.jpg",
      // },
      {
        selected: "",
        value: "albedoMat",
        name: "albedoMat",
        key: "albedoMat",
        url: "https://www.babylonjs-playground.com/textures/albedo.png",
      },
      {
        selected: "",
        value: "reflectivityMat",
        name: "reflectivityMat",
        key: "reflectivityMat",
        url: "https://www.babylonjs-playground.com/textures/reflectivity.png",
      },
    ],
  },
  {
    name: "bathroom_shower_walls",
    key: "bathroom_shower_walls",
    folder: "/mesh/bathroom_shower_walls/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [
      {
        selected: "selected",
        value: "bath1",
        name: "bath1",
        key: "bath1",
        url: "/mesh/bathroom_shower_walls/textures/bath1.jpg",
      },
      {
        selected: "",
        value: "bath2",
        name: "bath2",
        key: "bath2",
        url: "/mesh/bathroom_shower_walls/textures/bath2.jpg",
      },
      {
        selected: "",
        value: "bath3",
        name: "bath3",
        key: "bath3",
        url: "/mesh/bathroom_shower_walls/textures/bath3.jpg",
      },
    ],
  },
  {
    name: "floor_tube",
    key: "floor_tube",
    folder: "/mesh/bathroom_floor/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [
      {
        selected: "selected",
        value: "floor1",
        name: "floor1",
        key: "floor1",
        url: "/mesh/bathroom_floor/textures/floor1.jpg",
      },
      {
        selected: "",
        value: "floor2",
        name: "floor2",
        key: "floor2",
        url: "/mesh/bathroom_floor/textures/floor2.jpg",
      },
      {
        selected: "",
        value: "floor3",
        name: "floor3",
        key: "floor3",
        url: "/mesh/bathroom_floor/textures/floor3.jpg",
      },
    ],
  },
  {
    name: "floor_bathroom",
    key: "floor_bathroom",
    folder: "/mesh/bathroom_floor2/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "tube1",
    key: "tube1",
    folder: "/mesh/bathroom_tube1/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "tube2",
    key: "tube2",
    folder: "/mesh/bathroom_tube2/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "tube3",
    key: "tube3",
    folder: "/mesh/bathroom_tube3/",
    file: "bathroom.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 100, y: 100, z: 100 },
    color: null,
    textures: [],
  },
  {
    name: "faucet1",
    key: "faucet1",
    folder: "/mesh/faucet1/",
    file: "faucet1.obj",
    position: { x: 0, y: 0, z: 0 },
    rotation: { x: 0, y: 180, z: 0 },
    scaling: { x: 0.16, y: 0.16, z: 0.16 },
    color: null,
    textures: [],
  },
  {
    name: "faucet2",
    key: "faucet2",
    folder: "/mesh/faucet2/",
    file: "03_Herend_F5411CR.obj",
    position: { x: 0, y: 0, z: -15 },
    rotation: { x: 270, y: 0, z: 180 },
    scaling: { x: 5, y: 5, z: 5 },
    color: null,
    textures: [],
  },
  {
    name: "faucet3",
    key: "faucet3",
    folder: "/mesh/faucet3/",
    file: "othnmthdfr.obj",
    position: { x: 0, y: 0, z: 5 },
    rotation: { x: 0, y: 90, z: 0 },
    scaling: { x: 5, y: 5, z: 5 },
    color: null,
    textures: [],
  },
];

export const AssetsToLoad = [
  {
    name: "bathroom_1",
    key: "bathroom",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
  },
  {
    name: "bathroom_shower_glass_1",
    key: "bathroom_shower_glass",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    applyMaterial: null,
    applyColor: {
      r: 0,
      g: 0,
      b: 0,
      a: 100,
    },
    visible: true,
  },
  {
    name: "bathroom_walls_1",
    key: "bathroom_walls",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
    // applyMaterial: "albedoMat",
  },
  {
    name: "bathroom_shower_walls_1",
    key: "bathroom_shower_walls",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
  },
  {
    name: "floor_tube_1",
    key: "floor_tube",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
  },
  {
    name: "floor_bathroom_1",
    key: "floor_bathroom",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
  },
  {
    name: "tube1_1",
    key: "tube1",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: false,
  },
  
  {
    name: "tube2_1",
    key: "tube2",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: true,
  },
  {
    name: "tube3_1",
    key: "tube3",
    reference: null,
    onSuccess: () => { },
    onError: () => { },
    visible: false,
  },
  {
    name: "faucet1_1",
    key: "faucet1",
    reference: "faucetS1",
    onSuccess: () => { console.log("faucet1_1 loaded") },
    onError: () => { console.log("faucet1_1 failed") },
    visible: true,
  },
  {
    name: "faucet1_2",
    key: "faucet1",
    reference: "faucetS2",
    onSuccess: null,
    onError: null,
    visible: true,
  },
  {
    name: "faucet2_1",
    key: "faucet2",
    reference: "faucetS1",
    onSuccess: null,
    onError: null,
    visible: false,
  },
  {
    name: "faucet2_2",
    key: "faucet2",
    reference: "faucetS2",
    onSuccess: null,
    onError: null,
    visible: false,
  },
  {
    name: "faucet3_1",
    key: "faucet3",
    reference: "faucetS1",
    onSuccess: null,
    onError: null,
    visible: false,
    applyColor: {
      r: 255,
      g: 255,
      b: 255,
      a: 255,
    }
  },
  {
    name: "faucet3_2",
    key: "faucet3",
    reference: "faucetS2",
    onSuccess: null,
    onError: null,
    visible: false,
    applyColor: {
      r: 255,
      g: 255,
      b: 255,
      a: 255,
    }
  },
]

export const ShapesToLoad = [
  {
    method: "CreateBox",
    name: "faucetS1",
    size: 1,
    position: { x: -20, y: 100, z: 95 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 1, y: 1, z: 1 },
    color: { r: 255, g: 255, b: 255, a: 255 },
    textures: [],
    visible: true,
  },
  {
    method: "CreateBox",
    name: "faucetS2",
    size: 1,
    position: { x: 87, y: 100, z: 95 },
    rotation: { x: 0, y: 0, z: 0 },
    scaling: { x: 1, y: 1, z: 1 },
    color: { r: 255, g: 255, b: 255, a: 255 },
    textures: [],
    visible: true,
  },
]

export const ExchangeableAssets = [
  {
    name: "faucets",
    items: [
      "faucet1_1",
      "faucet1_2",
      "faucet2_1",
      "faucet2_2",
      "faucet3_1",
      "faucet3_2",
    ],
    groups: [
      {
        name: "faucet1",
        items: ["faucet1_1", "faucet1_2"],
      },
      {
        name: "faucet2",
        items: ["faucet2_1", "faucet2_2"],
      },
      {
        name: "faucet3",
        items: ["faucet3_1", "faucet3_2"],
      },
    ]
  }, 
  {
    name: "Tube",
    items: [
      "tube1_1",
      "tube2_1",
      "tube3_1",
    ],
    groups: [
      {
        name: "tube1",
        items: ["tube1_1"],
      },
      {
        name: "tube2",
        items: ["tube2_1"],
      },
      {
        name: "tube3",
        items: ["tube3_1"],
      },
    ]
  }, 
]

export const  TextureableAssets = [
  {
    name: "bathroom_walls_1",
    key: "bathroom_walls_1",
    // getTextures: () => ShapesToLoad.filter(({name}) => name === "WelcomeWall_1")[0].textures ,
    getTextures: () => Assets.filter(({name}) => name === "bathroom_walls")[0].textures ,
  },
  {
    name: "bathroom_shower_walls_1",
    key: "bathroom_shower_walls_1",
    getTextures: () => Assets.filter(({name}) => name === "bathroom_shower_walls")[0].textures ,
  },
  {
    name: "floor_tube_1",
    key: "floor_tube_1",
    getTextures: () => Assets.filter(({name}) => name === "floor_tube")[0].textures ,
  },
  {
    name: "floor_bathroom_1",
    key: "floor_bathroom_1",
    getTextures: () => Assets.filter(({name}) => name === "floor_tube")[0].textures ,
  },
]