using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace EditorStronglyTyped
{
    public class Menu
    {
        private static string _outputFolder = "StronglyTypedAutoGenerated";
        public static string OutputFolder { get => _outputFolder; private set => _outputFolder = value; }
        
        [MenuItem("StronglyTyped/Refresh All")]
        public static void RefreshAll()
        {
            Tags.DeleteAndRefresh();
            SortingLayers.DeleteAndRefresh();
            Layers.DeleteAndRefresh();
            Scenes.DeleteAndRefresh();
            Axes.DeleteAndRefresh();
        }
        [MenuItem("StronglyTyped/Delete All")]
        public static void DeleteAll()
        {
            Tags.Delete();
            SortingLayers.Delete();
            Layers.Delete();
            Scenes.Delete();
            Axes.Delete();
        }

        

        [MenuItem("StronglyTyped/Change output folder")]
        public static void ChangeSaveLocation()
        {
            string newOutputFolder = EditorUtility.OpenFolderPanel("Select output folder", Application.dataPath, "");
            if (string.IsNullOrEmpty(newOutputFolder))
                return;

            var currentPath = Application.dataPath;
            OutputFolder = newOutputFolder.Replace($"{currentPath}/", "").Replace(currentPath, "");

            Helper.SaveSettings("OutputFolder", OutputFolder);
        }
    }
}


